---
swagger: "2.0"
info:
  description: Contains all available API endpoints in this codebase
  version: "1.0"
  title: Bank Argent API documentation
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
- http
paths:
  /user/login:
    post:
      tags:
      - User Module
      summary: Login
      description: API for Login
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Login Payload
        required: true
        schema:
          $ref: '#/definitions/Login'
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
      - User Module
      summary: Signup
      description: API for Signup
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Signup Payload
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      tags:
      - User Module
      summary: User Profile API
      description: API for fetching a user profile
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      security:
      - Bearer: []
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      tags:
      - User Module
      summary: User Profile API
      description: API for updating a user profile
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      - in: body
        name: body
        description: Update user profile attributes
        required: true
        schema:
          $ref: '#/definitions/UserProfile'
      security:
      - Bearer: []
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transaction/{month}:
    get:
      tags:
      - User Module Transaction
      summary: User Transaction API
      description: API for fetching monthly user transaction
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      - name: month
        in: path
        description: month
        required: true
        type: integer
      security:
      - Bearer: []
      responses:
        "200":
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transaction/{id}:
    get:
      tags:
      - User Module Transaction
      summary: User Transaction API
      description: API for fetching one user transaction
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      - name: id
        in: path
        description: ID of the transaction to get
        required: true
        type: integer
      security:
      - Bearer: []
      responses:
        "200":
          description: User Transaction retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      tags:
      - User Module Transaction
      summary: User Transaction API
      description: API for updating a user transaction
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      - name: id
        in: path
        description: ID of the transaction to get
        required: true
        type: integer
      - in: body
        name: body
        description: Update user transaction
        required: true
        schema:
          $ref: '#/definitions/TransactionUpdate'
      security:
      - Bearer: []
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/TransactionUpdate'
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      tags:
      - User Module Transaction
      summary: User Transaction API
      description: API for delete a user transaction
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      - name: id
        in: path
        description: ID of the transaction to get
        required: true
        type: integer
      security:
      - Bearer: []
      responses:
        "200":
          description: User Transaction deleted successully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/ApiResponse_body'
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
    type: object
    properties:
      id:
        type: string
      transactionData:
        $ref: '#/definitions/Transaction_transactionData'
  TransactionUpdate:
    type: object
    properties:
      description:
        type: string
  ApiResponse_body:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
  Transaction_transactionData_detail:
    type: object
    properties:
      typeoftransaction:
        type: string
      category:
        type: string
      notes:
        type: string
  Transaction_transactionData:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      detail:
        $ref: '#/definitions/Transaction_transactionData_detail'
